name: Frontend Deploy

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Echo test
        run: echo "✅ GitHub Actions workflow triggered successfully!"

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install & Build
        working-directory: frontend
        run: |
          npm ci
          npm run build
